name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.dckr_pat_KUsUJ09IzthB0M-3e8yHA893yhI }}" | docker login -u "${{ secrets.rexdroid }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rexdroid/sentiment-app:latest

    - name: Push the Docker image
      run: docker push rexdroid/sentiment-app:latest
